name: "dropwizard-ci-pipeline"

on:
  push:
    branch:
      - main

jobs:
  build-and-test:
    runs-on: self-hosted-lab-runner
    steps:
      - uses: rtCamp/action-cleanup@master
      - uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        working-directory: .
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Test
        working-directory: .
        run: ./gradlew test

#  deploy:
#    needs: build-and-test
#    runs-on: self-hosted-rafid
#    steps:
#      - uses: rtCamp/action-cleanup@master
#      - uses: actions/checkout@master
#
#      - name: Copy repo to VM
#        uses: appleboy/scp-action@master
#        env:
#          HOST: ${{ secrets.HOST }}
#          USERNAME: ${{ secrets.USERNAME }}
#          PORT: ${{ secrets.PORT }}
#          KEY: ${{ secrets.KEY }}
#        with:
#          source: "./"
#          target: "~/prod"
#
#      - name: Deploy
#        uses: appleboy/ssh-action@master
#        with:
#          HOST: ${{ secrets.HOST }}
#          USERNAME: ${{ secrets.USERNAME }}
#          PORT: ${{ secrets.PORT }}
#          KEY: ${{ secrets.KEY }}
#          script: |
#            cd ~/prod
#            docker-compose down && docker-compose up --build -d
#
#
#
#
